platforms: [linux/amd64, linux/arm64]
context: images/ubuntu
tag: ubuntu
versions:
  "20.04":
    dockerfile: |
      FROM ubuntu:20.04
  "22.04":
    dockerfile: |
      FROM ubuntu:22.04
  "24.04":
    dockerfile: |
      FROM ubuntu:24.04
