platforms: [linux/amd64, linux/arm64]
context: images/python
tag: python
versions:
  3.10-alpine3.21:
    dockerfile: |
      FROM python:3.10-alpine3.21
  3.11-alpine3.21:
    dockerfile: |
      FROM python:3.11-alpine3.21
  3.12-alpine3.21:
    dockerfile: |
      FROM python:3.12-alpine3.21
  3.10-bookworm:
    dockerfile: |
      FROM python:3.10-bookworm
  3.11-bookworm:
    dockerfile: |
      FROM python:3.11-bookworm
  3.10-bullseye:
    dockerfile: |
      FROM python:3.10-bullseye
  3.11-bullseye:
    dockerfile: |
      FROM python:3.11-bullseye
